# Generated by Django 5.1.6 on 2025-02-23 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.CharField(null=True)),
                ('department', models.CharField(null=True)),
                ('job_role', models.CharField(null=True)),
                ('job_type', models.CharField(null=True)),
                ('salary', models.CharField(null=True)),
                ('number_of_position', models.CharField(null=True)),
                ('qulification', models.CharField(null=True)),
                ('experience', models.CharField(null=True)),
                ('job_description', models.CharField(null=True)),
                ('address', models.CharField(null=True)),
                ('last_apply_data', models.CharField(null=True)),
                ('interview_mode', models.CharField(null=True)),
                ('institute_img', models.ImageField(default='Image Currently Unavailable', null=True, upload_to='institute_images/')),
                ('institute_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.CharField(null=True)),
                ('date_of_birth', models.CharField(null=True)),
                ('gender', models.CharField(null=True)),
                ('Education', models.CharField(null=True)),
                ('country', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('search_role', models.CharField(null=True)),
                ('experience', models.CharField(null=True)),
                ('remote', models.CharField(null=True)),
                ('Staff_img', models.ImageField(null=True, upload_to='staff_images/')),
                ('staff_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
