# Generated by Django 5.1.6 on 2025-02-23 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_applied_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.CharField(null=True)),
                ('gender', models.CharField(null=True)),
                ('dob', models.CharField(null=True)),
                ('address', models.CharField(null=True)),
                ('Education', models.CharField(null=True)),
                ('job_role', models.CharField(null=True)),
                ('experience', models.CharField(null=True)),
                ('resume', models.FileField(null=True, upload_to='staff_resume/')),
                ('institute_reference', models.CharField(null=True)),
                ('staff_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
