# Generated by Django 5.1.6 on 2025-02-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_Form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='institute_hire_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneo_no', models.CharField(null=True)),
                ('address', models.CharField(null=True)),
                ('hire_role', models.CharField(null=True)),
                ('salary', models.CharField(null=True)),
                ('subject', models.CharField(null=True)),
                ('hire_staff', models.CharField(null=True)),
                ('institute_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
